name: Build master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Gradle build with test coverage
        run: ./gradlew dabirva:jacocoTestReportRelease --console=plain --full-stacktrace
      - name: Upload code coverage results to codecov
        uses: codecov/codecov-action@v1
        with:
          directory: ./dabirva/build/reports/jacoco/
          fail_ci_if_error: true
