name: Build master

on: [push, pull_request]

jobs:
  build-and-test:
    name: Build and test
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Assemble release using Gradle
        run: ./gradlew dabirva:assembleRelease --console=plain --full-stacktrace

      - name: Run unit tests with coverage using Gradle
        run: ./gradlew dabirva:jacocoTestReportRelease --console=plain --full-stacktrace

      - name: Run instrumented tests with coverage using Gradle
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew dabirva:connectedReleaseAndroidTest --console=plain --full-stacktrace

      - name: Merge test results
        run: cd dabirva/build/ && mkdir -v _test-results && mv -v test-results _test-results/ && mv -v outputs/androidTest-results _test-results/

      - name: Merge test coverage
        run: cd dabirva/build/ && mkdir -v _test-coverage && mv -v jacoco _test-coverage/ && mv -v outputs/code_coverage _test-coverage/

      # https://github.com/marketplace/actions/publish-unit-test-results
      - name: Publish test results to GitHub
        uses: EnricoMi/publish-unit-test-result-action@v1.7
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: ./dabirva/build/_test-results/**/*.xml

      # https://github.com/marketplace/actions/codecov
      - name: Publish test coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          directory: ./dabirva/build/_test-coverage/
          fail_ci_if_error: true
