name: check

on:
  push:

env:
  GRADLEW_ARGUMENTS: "--console=plain --stacktrace -Pci -Pcoverage"

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # https://github.com/marketplace/actions/setup-java-jdk
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # https://github.com/gradle/actions/blob/main/setup-gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Check public API
        run: ./gradlew dabirva:apiCheck $GRADLEW_ARGUMENTS

      - name: Run Android lint
        run: ./gradlew dabirva:lintDebug $GRADLEW_ARGUMENTS

      - name: Print Android lint results
        run: cat ./dabirva/build/reports/lint-results-debug.xml

      - name: Run unit tests with coverage
        run: ./gradlew dabirva:testDebugUnitTest $GRADLEW_ARGUMENTS

      # https://github.com/marketplace/actions/android-emulator-runner
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Run instrumented tests with coverage
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 35
          arch: x86_64
          script: ./gradlew example:connectedDebugAndroidTest $GRADLEW_ARGUMENTS

      - name: Merge test coverage reports
        run: ./gradlew jacocoMergedReportDebug $GRADLEW_ARGUMENTS

      # https://github.com/marketplace/actions/surefire-report
      - name: Publish test results to GitHub
        uses: ScaCap/action-surefire-report@v1
        if: ${{ always() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: ./*/build/test-results/**/*.xml

      # https://github.com/marketplace/actions/codecov
      - name: Publish test coverage to codecov
        uses: codecov/codecov-action@v5
        with:
          directory: ./build/reports/jacoco/jacocoMergedReportDebug
          fail_ci_if_error: true
