name: check

on:
  push:
    branches:
      # Trigger for pushes to develop to run when merging feature branches using squashing
      - develop
  pull_request:

env:
  GRADLEW_ARGUMENTS: "--console=plain --stacktrace -Pci"

jobs:
  build_and_test:
    runs-on: macos-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v2

      # https://github.com/marketplace/actions/gradle-wrapper-validation
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      # https://github.com/marketplace/actions/setup-java-jdk
      - name: Setup JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Setup Gradle
        run: ./gradlew --version

      - name: Check public API
        run: ./gradlew dabirva:apiCheck $GRADLEW_ARGUMENTS

      - name: Run Android lint
        run: ./gradlew dabirva:lintRelease $GRADLEW_ARGUMENTS

      - name: Print Android lint results
        run: cat ./dabirva/build/reports/lint-results-release.xml

      - name: Run unit tests with coverage
        run: ./gradlew dabirva:jacocoTestReportDebug $GRADLEW_ARGUMENTS

      # https://github.com/marketplace/actions/android-emulator-runner
      - name: Run instrumented tests with coverage
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew example:connectedDebugAndroidTest $GRADLEW_ARGUMENTS

      - name: Merge test coverage reports
        run: ./gradlew collectDabirvaCoverageDebug $GRADLEW_ARGUMENTS

      # https://github.com/marketplace/actions/surefire-report
      - name: Publish test results to GitHub
        uses: scacap/action-surefire-report@v1
        if: ${{ always() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: ./dabirva/build/test-results/**/*.xml

      # https://github.com/marketplace/actions/codecov
      - name: Publish test coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          directory: ./build/reports/jacoco/collectDabirvaCoverageDebug/
          fail_ci_if_error: true
