name: publish

on:
  push:
    branches:
      - develop
      - master

env:
  GRADLEW_ARGUMENTS: "--console=plain --stacktrace -Pci"

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # https://github.com/marketplace/actions/setup-java-jdk
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # https://github.com/gradle/actions/blob/main/setup-gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Add publishing secrets
        env:
          SIGNING_KEY_CONTENT_BASE64: ${{ secrets.SIGNING_KEY_CONTENT_BASE64 }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        run: |
          cd
          echo "$SIGNING_KEY_CONTENT_BASE64" | base64 --decode > key.gpg
          echo "signing.keyId=$SIGNING_KEY_ID" >> .gradle/gradle.properties
          echo "signing.password=$SIGNING_KEY_PASSWORD" >> .gradle/gradle.properties
          echo "signing.secretKeyRingFile=$(pwd)/key.gpg" >> .gradle/gradle.properties
          echo "mavenCentralUsername=$MAVEN_CENTRAL_USERNAME" >> .gradle/gradle.properties
          echo "mavenCentralPassword=$MAVEN_CENTRAL_PASSWORD" >> .gradle/gradle.properties

      - name: Publish to Central Portal
        if: startsWith(github.ref, 'refs/heads/release/')
        run: ./gradlew dabirva:publishMavenPublicationToMavenCentralRepository $GRADLEW_ARGUMENTS
